#!groovy

import groovy.json.JsonSlurper

pipeline {
    agent any

   stages {

        stage('Parse') {
            steps {
                println new JsonSlurper().parseText(env.payload)
            }
        }
   }
}
